pizarra/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]


pizarra/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

pizarra/pizarra/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('' , include("account.urls")),
    path('projects/', include("project.urls")),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
    path('healthz/', lambda _: HttpResponse("OK")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizarra/project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.project, name='project'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
    path('<uuid:pk>/back/', views.back, name='back'),
    path('<uuid:project_id>/files/upload_file', views.upload_file, name='upload_file'),
    path('<uuid:project_id>/files/<uuid:pk>/delete/', views.delete_file, name='delete_file'),
    path('<uuid:project_id>/notes/add_note/', views.add_note, name='add_note'),  # Added trailing slash
    path('<uuid:project_id>/notes/<uuid:pk>/', views.note_detail, name='note_detail'),
    path('<uuid:project_id>/notes/<uuid:pk>/edit/', views.edit_note, name='edit_note'),
    path('<uuid:project_id>/notes/<uuid:pk>/delete/', views.delete_note, name='delete_note'),
    path('<uuid:project_id>/notes/back_note/', views.back_note, name='back_note'),
]

pizarra/core/models.py
from django.db import models

# Create your models here.

pizarra/core/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'core/index.html')

def about(request):
    return render(request, 'core/about.html')

pizarra/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block content %}
<h1 class="text-3xl">About</h1>
<div class="mt-6 space-y-6">
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam
    cupiditate blanditiis libero molestias officia. Illum, culpa iure odit
    nesciunt recusandae unde ducimus doloribus voluptas in maiores
    pariatur excepturi perspiciatis aliquid.
  </p>

  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Totam
    cupiditate blanditiis libero molestias officia. Illum, culpa iure odit
    nesciunt recusandae unde ducimus doloribus voluptas in maiores
    pariatur excepturi perspiciatis aliquid.
  </p>
</div>
{% endblock %}

pizarra/core/templates/core/base.html
{% load compress %}
{% load static %}
<!doctype html>
<html class="h-full" lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}Pizarra</title>
  
  {% compress css %}
  <link href="{% static 'css/output.css' %}" rel="stylesheet">
  {% endcompress %}
  {% comment %} Remove this line since we're using compiled CSS
  <script src="https://cdn.tailwindcss.com"></script>
  {% endcomment %}

  <style>
    html, body {
      height: 100;
    }
  </style>
</head>
<body class="h-full flex flex-col" >
    <nav class="py-6 px-8 flex items-center justify-between bg-slate-800">
        <h1 class="text-xl text-white" >
            <a href="{% url 'core:index' %}">Pizarra</a>
        </h1>
        
        <div class="space-x-4">
            <a href="{% url 'core:about' %}" class="text-white">About</a>

            {% if request.user.is_authenticated %}
            <a href="{% url 'project:projects' %}" class="btn-submit">Projects</a>
            <a href="{% url 'account:logout' %}" class="btn-delete">Log out</a>
            {% else %}
            <a href="{% url 'account:login' %}" class="btn-back">Log in</a>
            <a href="{% url 'account:signup' %}" class="btn-submit">sign up</a>
            {% endif %}

        </div>
    </nav>
    <main class="flex-1 py-6 px-8">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="py-8 px-8 bg-slate-900 text-white  mt-auto text-center">
        <p class= "text-white">
            Copyright (c) 2023 - Code With Hamid
        </p>
    </footer>
</body>
</html>

pizarra/core/templates/core/index.html

{% extends "core/base.html" %}

{% block content %}
    <header class = "py-12 text-center bg-slate-200">
        <h1 class="text-3xl">Welcome to Pizarra</h1>
    </header>
{% endblock %}