pizarra/core/urls.py
from django.urls import path
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
]

pizarra/pizarra/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('' , include("account.urls")),
    path('projects/', include("project.urls")),
    path('projects/<uuid:project_id>/', include('todolist.urls')),
    path('projects/<uuid:project_id>/<uuid:todolist_id>/', include('task.urls')),
    path('healthz/', lambda _: HttpResponse("OK")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pizarra/task/urls.py
from django.urls import path
from . import views

app_name = 'task'

urlpatterns = [
    path('add/', views.add, name='add'),
    path('<uuid:pk>/', views.task, name='task'),
    path('<uuid:pk>/edit/', views.edit, name='edit'),
    path('<uuid:pk>/delete/', views.delete, name='delete'),
    path('<uuid:pk>/back/', views.back, name='back'),
]

pizarra/task/models.py
from django.db import models
import uuid
from todolist.models import TodoList
from account.models import User
from project.models import Project

class Task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    project = models.ForeignKey(Project, related_name='tasks', on_delete=models.CASCADE)
    todolist = models.ForeignKey(TodoList, related_name='tasks', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='tasks', on_delete=models.CASCADE)
    description = models.TextField(blank=True, null=True)
    
    is_done = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

pizarra/task/views.py
from django.shortcuts import render, redirect
from project.models import Project
from todolist.models import TodoList
from .models import Task
from django.contrib.auth.decorators import login_required

@login_required
def task(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = TodoList.objects.filter(project=project).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)
    
        
    if 'toggle_done' in request.GET:
        task.is_done = not task.is_done
        task.save()
    
    return render(request, 'task/task.html', {
        'task': task  
    })
    
@login_required
def add(request, project_id, todolist_id):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = TodoList.objects.filter(project=project_id).get(pk=todolist_id)
    
    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')
        
        if name and description:
            Task.objects.create(name=name, description=description, project=project, todolist=todolist, created_by=request.user)
            
            return redirect(f'/projects/{project_id}/{todolist_id}/')
    
    return render(request, 'task/add.html', {
        'project': project,
        'todolist': todolist
    })


@login_required
def delete(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = TodoList.objects.filter(project=project_id).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)
    task.delete()
    return redirect(f'/projects/{project_id}/{todolist_id}/')


@login_required
def edit(request, project_id, todolist_id, pk):
    project = Project.objects.filter(created_by=request.user).get(pk=project_id)
    todolist = TodoList.objects.filter(project=project_id).get(pk=todolist_id)
    task = Task.objects.filter(project=project).filter(todolist=todolist).get(pk=pk)
    
    if request.method == 'POST':
        name = request.POST.get('name', '')
        description = request.POST.get('description', '')
        
        if name:
            task.name = name
            
        task.description = description
        task.save()
        return redirect(f'/projects/{project_id}/{todolist_id}/{pk}/')

    return render(request, 'task/edit.html', {
        'task': task
    })


@login_required
def back(request, project_id, todolist_id, pk):
    return redirect(f'/projects/{project_id}/{todolist_id}/')

pizarra/task/templates/task/add.html
{% extends 'core/base.html'%}

{% block content %}
<h1 class="mb-6 text-3xl">Add task</h1>
<form class="mt-6 space-y-4" method="post" action=".">
    {% csrf_token %}
    <div>
        <label class="form-label">Name</label>
        <br>
        <input name="name" type="text" class="form-input">
        <br>
    </div>

    <div>
        <label class="form-label">Description</label>
        <br>
        <textarea name="description" class="form-textarea"></textarea>
    </div>


    <div>

        <button class="btn-submit">Submit</button>
    </div>
</form>
{% endblock %}

pizarra/task/templates/task/edit.html
{% extends 'core/base.html'%}

{% block content %}
<h1 class="mb-6 text-3xl">Edit task</h1>
<form class="mt-6 space-y-4" method="post" action=".">
    {% csrf_token %}
    <div>
        <label class="form-label">Name</label>
        <br>
        <input value=" {{ task.name }}"  name="name" type="text" class="form-input">
        <br>
    </div>

    <div>
        <label class="form-label">Description</label>
        <br>
        <textarea name="description" class="form-textarea">{{task.description}}</textarea>
    </div>

    <div>
        <button class="btn-submit">Submit</button>
    </div>
</form>
{% endblock %}

pizarra/task/templates/task/task.html
{% extends 'core/base.html'%}

{% block content %}

<h1 class="mb-6 text-3xl">{{ task.name }}</h1>

<p><strong class="font-bold">Status:</strong> {% if task.is_done %}Done{% else %} Todo {% endif %}</p>

{% if task.description %}
<p class="mb-6">{{ task.description }}</p>
{% endif %}

<a
  href="?toggle_done=true"
  class="py-4 px-8 {% if task.is_done %}btn-back{% else %}btn-add{% endif %} text-white inline-block"
>
  {% if task.is_done %}
    Mark as not done
  {% else %}
    Mark as done
  {% endif %}
</a>
<a href="{% url 'task:edit' task.project_id task.todolist_id  task.id %}" class="btn-edit">Edit</a>
<a href="{% url 'task:delete' task.project_id task.todolist_id task.id %}" class="btn-delete">Delete</a>
<a href="{% url 'task:back'  task.project_id task.todolist_id task.id %}" class="btn-back">Back</a>

{% endblock %}